    <footer class="page-footer font-small blue">

        <!-- footer boostrap css -->
        <div class="footer-copyright text-center py-3">
            <p>© 2025 University of Salford using the MVC design pattern and the Bootstrap CSS framework</p>
        </div>

    </footer>


<!-- Bootstrap core JavaScript
================================================== -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>


    <script src="/Views/js/bootstrap.js"></script>
